#!/bin/sh

echo "+++++++++install OpenAIL library start++++++++++"

VERSION=1.0.0
INSTALL_NAME=openail
INSTALL_DIR=/usr
INSTALL_INC_DIR=$INSTALL_DIR/include/$INSTALL_NAME
INSTALL_LIB_DIR=$INSTALL_DIR/lib

echo "include dir = $INSTALL_INC_DIR"
echo "lib dir     = $INSTALL_LIB_DIR"

mkdir $INSTALL_INC_DIR -p

# install libopenail
#copy head files
cp ./inc $INSTALL_INC_DIR -rf
cp openail $INSTALL_INC_DIR -rf
rm $INSTALL_LIB_DIR/libopenail.* -f
cp ./lib/* $INSTALL_LIB_DIR -f
ln -s $INSTALL_LIB_DIR/libopenail.$VERSION.so $INSTALL_LIB_DIR/libopenail.so

echo "lib list    = libopenail.so"
echo "++++++++install OpenAIL library success+++++++++"
