PRONAME:=openail
VERSION:=1.0.0
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(BUILD_PATH)/inc \
	/usr/include/duye \

LIBS_PATH:=/usr/lib 

LIBS:=logger

include ./shared.mk
